import { store } from '@/GlobalRedux/store'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'
import { Provider } from 'react-redux'
import { Providers } from '@/GlobalRedux/provider'
import StyledComponentsRegistry from '@/lib/AntdRegistry';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className={inter.className}>
        <Providers >
          <StyledComponentsRegistry>
            <Toaster />
            {children}
          </StyledComponentsRegistry>
        </Providers>
      </body>
    </html>
  )
}
